/* 1주차 학습 콘텐츠. 각 예제는 독립적으로 실행됩니다. */
window.LESSONS = [
  {
    "id": 1,
    "title": "첫 번째 코드 실행",
    "minutes": 30,
    "examples": [
      "print(\"나의 첫 데이터 분석\")\nprint(4500 + 8000)",
      "print(5000 + 8000)",
      "# 교통비 3000원과 간식비 2500원을 더해 출력하세요.\n"
    ],
    "outputs": [
      "나의 첫 데이터 분석\n12500",
      "13000",
      null
    ],
    "solution": "print(3000 + 2500)",
    "solutionOutput": "5500",
    "pages": [
      "<h1>컴퓨터에게<br>첫 계산을 부탁해요.</h1><p class=\"intro\">커피 한 잔 4,500원, 점심 한 끼 8,000원.<br>오늘 쓴 돈을 파이썬으로 더해볼까요?</p><div class=\"goal\"><b>오늘의 목표</b><span>코드를 실행하고, 숫자를 바꿔 다시 실행할 수 있어요.</span></div><h2 class=\"section-title\"><span>1</span> 코드를 실행해 보세요</h2><p>오른쪽 입력 칸이 코드를 쓰는 공간이에요. 아래 예제를 불러온 뒤 <b>실행하기</b>를 눌러보세요.</p><div class=\"example\"><pre>print(\"나의 첫 데이터 분석\")\nprint(4500 + 8000)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><ul class=\"terms\"><li><code>print()</code> 괄호 안의 내용을 화면에 보여줘요.</li><li><code>\" \"</code> 글자는 따옴표로 감싸요.</li><li><code>+</code> 숫자와 숫자를 더해요.</li></ul><h2 class=\"section-title\"><span>2</span> 결과를 비교해 보세요</h2><div class=\"example\"><pre>나의 첫 데이터 분석\n12500</pre></div><p>첫 줄에는 문장이, 둘째 줄에는 계산 결과가 나와요.<br>내 화면에도 같은 결과가 나타났나요?</p>",
      "<h1>숫자 하나를 바꾸면<br>결과도 달라질까요?</h1><p class=\"intro\">코드를 모두 외울 필요는 없어요.<br>작은 부분을 바꾸며 차이를 발견해 보세요.</p><div class=\"goal\"><b>오늘의 실험</b><span>실행 전에 예상하고, 실행 후에 확인해요.</span></div><h2 class=\"section-title\"><span>3</span> 커피값이 올랐어요</h2><p>커피값이 4,500원에서 <b>5,000원</b>으로 바뀌었어요. 점심값은 그대로 8,000원이에요.</p><p><label for=\"a-predict\">바뀐 합계는 얼마일까요? 먼저 예상해 보세요.</label></p><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"예상한 금액과 이유를 적어보세요.\"></textarea><div class=\"example\"><pre>print(5000 + 8000)</pre><button class=\"load\" data-example=\"1\">바뀐 예제로 실습하기</button></div><p>코드를 수정한 뒤에는 <b>실행하기</b>를 다시 눌러야 새로운 결과가 나타나요.</p><details class=\"hint\"><summary>결과와 설명 확인하기</summary><p>결과는 <b>13000</b>이에요. 커피값이 500원 올랐으니 합계도 12500에서 13000으로 500 증가해요.</p></details><h2 class=\"section-title\"><span>4</span> 결과를 내 말로 설명해요</h2><p><label for=\"a-change\">어느 숫자를 바꿨고, 결과는 어떻게 달라졌나요?</label></p><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"나는 …을 바꿨고, 결과는 …\"></textarea><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 사람이 금액을 바꾸면 다른 사람은 실행 결과를 예상해요. 답을 확인한 뒤 역할을 바꿔보세요.</p></details>",
      "<h1>이번에는<br>혼자 해볼 차례예요.</h1><p class=\"intro\">조금 막혀도 괜찮아요.<br>힌트를 하나씩 열어보며 완성해 보세요.</p><div class=\"goal\"><b>나의 첫 미션</b><span>두 금액의 합계를 화면에 출력해요.</span></div><h2 class=\"section-title\"><span>5</span> 오늘의 작은 문제</h2><p>교통비 <b>3,000원</b>과 간식비 <b>2,500원</b>을 썼어요. 두 금액의 합계를 출력하는 코드를 작성하세요.</p><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button><details class=\"hint\"><summary>힌트 1 · 무엇을 사용하나요?</summary><p>화면에 보여줄 때는 print(), 숫자를 더할 때는 +를 사용해요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드의 모양이 궁금해요</summary><p><code>print(첫 번째 금액 + 두 번째 금액)</code>에서 두 금액을 숫자로 바꿔보세요.</p></details><details class=\"hint\"><summary>정답과 해설 확인하기</summary><div class=\"example\"><pre>print(3000 + 2500)</pre></div><p>결과는 <b>5500</b>이에요. 괄호 안의 덧셈을 계산한 다음 print()가 화면에 보여줘요. 계산할 숫자에는 따옴표를 붙이지 않아요.</p></details><h2 class=\"section-title\"><span>6</span> 오늘의 배움을 남겨요</h2><label for=\"a-learn\">코드를 바꾼 뒤 결과를 바꾸려면 무엇을 해야 하나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"한 문장으로 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 코드를 직접 실행했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 숫자를 바꾸고 결과를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 두 금액의 합계를 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 2,
    "title": "숫자로 계산하기",
    "minutes": 30,
    "examples": [
      "print(20000 - 4500 - 8000)\nprint(4500 * 2)\nprint((4500 + 8000) / 2)",
      "print(4500 + 8000 / 2)\nprint((4500 + 8000) / 2)",
      "# 6000원짜리 샌드위치 2개와 음료 3000원\n# 총액과, 총액을 3명이 똑같이 나눈 금액을 출력하세요.\n"
    ],
    "outputs": [
      "7500\n9000\n6250.0",
      "8500.0\n6250.0",
      null
    ],
    "solution": "print(6000 * 2 + 3000)\nprint((6000 * 2 + 3000) / 3)",
    "solutionOutput": "15000\n5000.0",
    "pages": [
      "<h1>파이썬을<br>계산기로 써볼까요?</h1><p class=\"intro\">남은 돈, 두 잔의 가격, 함께 낼 돈.<br>계산 기호를 바꾸면 다른 질문에 답할 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>더하기·빼기·곱하기·나누기를 사용할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · print(3000 + 2500)의 결과는?</summary><p>5500이에요. 괄호 안을 계산한 결과를 print()가 보여줘요.</p></details><h2 class=\"section-title\"><span>1</span>계산 기호 네 가지</h2><table class=\"lesson-table\"><thead><tr><th>기호</th><th>하는 일</th><th>예</th></tr></thead><tbody><tr><td>+</td><td>더하기</td><td>3 + 2 → 5</td></tr><tr><td>-</td><td>빼기</td><td>3 - 2 → 1</td></tr><tr><td>*</td><td>곱하기</td><td>3 * 2 → 6</td></tr><tr><td>/</td><td>나누기</td><td>6 / 2 → 3.0</td></tr></tbody></table><h2 class=\"section-title\"><span>2</span>세 가지 질문을 계산해요</h2><p>① 2만 원에서 커피와 점심값을 빼면?<br>② 커피 두 잔은 얼마일까요?<br>③ 커피와 점심값의 합계를 둘이 똑같이 나누면?</p><div class=\"example\"><pre>print(20000 - 4500 - 8000)\nprint(4500 * 2)\nprint((4500 + 8000) / 2)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 설명</summary><div class=\"example\"><pre>7500\n9000\n6250.0</pre></div><p><code>/</code>로 나눈 결과는 이 예시처럼 소수점이 있는 숫자로 나와요. <code>6250.0</code>과 <code>6250</code>은 수치상 같아요.</p></details>",
      "<h1>괄호가 바꾸는<br>계산의 순서</h1><p class=\"intro\">컴퓨터는 왼쪽부터 무조건 계산하지 않아요.<br>우리가 원하는 순서를 괄호로 알려줄 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>괄호를 사용해 합계를 먼저 계산할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>어느 계산이 맞을까요?</h2><p>4,500원과 8,000원을 더한 <b>전체 금액</b>을 둘로 나누고 싶어요. 다음 두 줄은 같은 결과가 나올까요?</p><div class=\"example\"><pre>print(4500 + 8000 / 2)\nprint((4500 + 8000) / 2)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">두 줄의 결과를 실행 전에 예상해 보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 풀이 확인</summary><div class=\"example\"><pre>8500.0\n6250.0</pre></div><p>곱하기·나누기를 더하기·빼기보다 먼저 계산해요. 첫 줄은 8000만 2로 나눈 뒤 4500을 더해요. 둘째 줄은 괄호 속 합계 12500을 먼저 구한 뒤 2로 나눠요.</p></details><h2 class=\"section-title\"><span>4</span>인원수를 바꿔봐요</h2><p>둘째 줄의 <code>/ 2</code>를 <code>/ 4</code>로 바꾸고 실행하세요. 네 사람이 같은 금액을 낸다면 얼마일까요?</p><label class=\"question\" for=\"a-change\">변경한 결과와 그 의미를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>3125.0이 나와요. 12500원을 네 사람이 나눠 낼 때 한 사람이 부담하는 금액이에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 말로 계산 상황을 설명하고, 다른 한 명은 괄호가 필요한 위치를 짚어보세요.</p></details>",
      "<h1>함께 먹은 간식값을<br>나눠 계산해요.</h1><p class=\"intro\">문장을 계산식으로 바꾸는 연습이에요.<br>한 번에 어렵다면 총액부터 구해보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>총액과 1인당 금액을 두 줄로 출력할 수 있어요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>6,000원짜리 샌드위치 <b>2개</b>와 3,000원짜리 음료 <b>1개</b>를 샀어요. 총액을 출력하고, 그 총액을 <b>3명</b>이 똑같이 나눈 금액도 출력하세요.</p><div class=\"example\"><pre># 6000원짜리 샌드위치 2개와 음료 3000원\n# 총액과, 총액을 3명이 똑같이 나눈 금액을 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 총액부터 구해요</summary><p>샌드위치 가격에 개수를 곱하고 음료값을 더해요.</p></details><details class=\"hint\"><summary>힌트 2 · 나누기 전에 묶어요</summary><p>총액을 구하는 식 전체를 괄호로 묶고 3으로 나누세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>print(6000 * 2 + 3000)\nprint((6000 * 2 + 3000) / 3)</pre></div><div class=\"example\"><pre>15000\n5000.0</pre></div><p>샌드위치 합계 12000원에 음료 3000원을 더하면 15000원이에요. 이를 3으로 나누면 1인당 5000원이에요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">합계를 나누기 전에 괄호를 쓰는 이유는 무엇인가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 네 가지 계산 기호를 실행했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 괄호 유무에 따른 차이를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 총액과 1인당 금액을 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 3,
    "title": "값에 이름 붙이기",
    "minutes": 35,
    "examples": [
      "coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\nprint(total)",
      "coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\ncoffee = 5000\nprint(total)\ntotal = coffee + lunch\nprint(total)",
      "# 교통비와 간식비에 이름을 붙여 합계를 구하세요.\ntransport = 3000\nsnack = 2500\n"
    ],
    "outputs": [
      "12500",
      "12500\n13000",
      null
    ],
    "solution": "transport = 3000\nsnack = 2500\ntotal = transport + snack\nprint(\"합계:\", total)",
    "solutionOutput": "합계: 5500",
    "pages": [
      "<h1>숫자에 이름을<br>붙여보세요.</h1><p class=\"intro\">4500이 무슨 금액이었는지 헷갈리나요?<br>이름이 있으면 코드의 뜻을 읽기 쉬워져요.</p><div class=\"goal\"><b>오늘의 목표</b><span>변수에 값을 넣고 계산에 사용할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · (6000 * 2 + 3000) / 3의 결과는?</summary><p>5000.0이에요. 총액 15000을 3으로 나눈 값이에요.</p></details><h2 class=\"section-title\"><span>1</span>변수는 값을 가리키는 이름이에요</h2><p><code>coffee = 4500</code>은 “coffee라는 이름으로 4500을 사용하겠다”는 뜻이에요. <code>=</code>는 오른쪽 값을 왼쪽 이름에 넣는 <b>대입</b> 기호예요.</p><div class=\"example\"><pre>coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\nprint(total)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>12500</pre></div><p>파이썬은 위에서 아래로 실행해요. 먼저 두 금액을 정한 뒤, 그 합계를 total에 넣어요.</p></details><h2 class=\"section-title\"><span>2</span>이름을 읽어보세요</h2><ul class=\"terms\"><li><code>coffee</code>는 커피값, <code>lunch</code>는 점심값이에요.</li><li><code>total</code>은 합계라는 뜻으로 우리가 정한 이름이에요.</li><li>변수를 쓸 때는 따옴표를 붙이지 않아요. <code>\"total\"</code>은 글자 자체예요.</li><li>영문 소문자와 밑줄을 활용해요. <code>snack_price</code>처럼 쓸 수 있어요. 공백은 넣지 않고 숫자로 시작하지 않아요.</li></ul>",
      "<h1>값을 바꾸면<br>합계도 따라 바뀔까요?</h1><p class=\"intro\">계산한 값은 그 순간의 결과예요.<br>입력값이 바뀌면 합계도 다시 계산해야 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>코드의 실행 순서와 재계산을 설명할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>먼저 예상하고 실행해요</h2><div class=\"example\"><pre>coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\ncoffee = 5000\nprint(total)\ntotal = coffee + lunch\nprint(total)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">두 print()는 각각 얼마를 보여줄까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>12500\n13000</pre></div><p>첫 total은 4500 + 8000의 결과인 12500이에요. coffee를 바꿔도 이미 계산한 total은 그대로예요. <code>total = coffee + lunch</code>를 다시 실행해야 13000이 돼요.</p></details><h2 class=\"section-title\"><span>4</span>설명을 붙여 출력해요</h2><p><code>print(\"합계:\", total)</code>처럼 쉼표로 구분하면 글자와 숫자를 함께 출력할 수 있어요. 기본적으로 둘 사이에 공백이 들어가요. 마지막 줄을 이 형태로 바꿔보세요.</p><label class=\"question\" for=\"a-change\">수정한 마지막 줄과 실행 결과를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><div class=\"example\"><pre>print(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 13000</pre></div></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 줄씩 읽으면서 coffee와 total이 현재 어떤 값을 가리키는지 번갈아 말해보세요.</p></details>",
      "<h1>이름을 활용해<br>지출을 정리해요.</h1><p class=\"intro\">숫자를 반복해서 쓰는 대신<br>의미가 있는 이름으로 계산해 보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>변수 두 개로 합계를 구하고 설명과 함께 출력해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>교통비는 3,000원, 간식비는 2,500원이에요. <code>transport</code>와 <code>snack</code>의 합계를 <code>total</code>에 넣고, <code>합계: 5500</code>이 나타나도록 출력하세요.</p><div class=\"example\"><pre># 교통비와 간식비에 이름을 붙여 합계를 구하세요.\ntransport = 3000\nsnack = 2500\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 값을 먼저 정해요</summary><p>변수는 사용하기 전에 값을 넣어야 해요. 두 변수를 먼저 정하고 합계를 계산하세요.</p></details><details class=\"hint\"><summary>힌트 2 · 출력할 때는 쉼표를 써요</summary><p><code>print(\"합계:\", total)</code>로 글자와 숫자를 함께 출력해요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>transport = 3000\nsnack = 2500\ntotal = transport + snack\nprint(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 5500</pre></div><p>total은 두 변수의 합계를 가리켜요. 교통비를 바꾸려면 첫 줄을 수정한 뒤 코드 전체를 다시 실행하면 돼요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">coffee를 바꾼 뒤 total을 다시 계산해야 하는 이유는 무엇인가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 변수를 만들고 사용했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 값을 바꾼 뒤 합계를 다시 계산했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 글자와 합계를 함께 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 4,
    "title": "문자와 숫자 구별하기",
    "minutes": 35,
    "examples": [
      "print(3000 + 2500)\nprint(\"3000\" + \"2500\")\nprint(type(3000))\nprint(type(3.5))\nprint(type(\"3000\"))",
      "price_text = \"4500\"\nprice = int(price_text)\nprint(price + 500)",
      "# 문자로 저장된 두 금액을 숫자로 바꾸고 더하세요.\ntransport_text = \"3000\"\nsnack_text = \"2500\"\n"
    ],
    "outputs": [
      "5500\n30002500\n<class 'int'>\n<class 'float'>\n<class 'str'>",
      "5000",
      null
    ],
    "solution": "transport_text = \"3000\"\nsnack_text = \"2500\"\ntotal = int(transport_text) + int(snack_text)\nprint(\"합계:\", total)",
    "solutionOutput": "합계: 5500",
    "pages": [
      "<h1>같아 보이지만<br>다른 데이터예요.</h1><p class=\"intro\">3000과 \"3000\"은 눈으로 보면 비슷해요.<br>파이썬은 둘을 다르게 다뤄요.</p><div class=\"goal\"><b>오늘의 목표</b><span>숫자와 문자열을 구별할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · print(\"합계:\", total)에서 따옴표를 붙인 것은?</summary><p>합계:는 보여줄 글자라서 따옴표를 붙여요. total은 변수의 값을 쓰므로 따옴표를 붙이지 않아요.</p></details><h2 class=\"section-title\"><span>1</span>따옴표가 의미를 바꿔요</h2><div class=\"example\"><pre>print(3000 + 2500)\nprint(&quot;3000&quot; + &quot;2500&quot;)\nprint(type(3000))\nprint(type(3.5))\nprint(type(&quot;3000&quot;))</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><p><code>type()</code>은 값의 종류, 즉 <b>자료형</b>을 알려줘요. <code>print(type(값))</code>으로 종류를 화면에 보여줄 수 있어요.</p><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>5500\n30002500\n&lt;class &#x27;int&#x27;&gt;\n&lt;class &#x27;float&#x27;&gt;\n&lt;class &#x27;str&#x27;&gt;</pre></div><p>숫자끼리 +를 쓰면 덧셈이에요. 문자열끼리 +를 쓰면 글자가 이어져요. <code>\"3000\"</code>과 <code>\"2500\"</code>이 이어져 <code>30002500</code>이 돼요.</p></details><h2 class=\"section-title\"><span>2</span>오늘 기억할 세 가지</h2><table class=\"lesson-table\"><thead><tr><th>자료형</th><th>뜻</th><th>예</th></tr></thead><tbody><tr><td>int</td><td>정수</td><td>3000</td></tr><tr><td>float</td><td>소수점이 있는 수</td><td>3.5</td></tr><tr><td>str</td><td>문자열</td><td>\"3000\"</td></tr></tbody></table><p>출력 모양만 보고 종류를 단정하기 어려울 때는 <code>type()</code>으로 확인해요.</p>",
      "<h1>글자로 된 금액을<br>계산하려면?</h1><p class=\"intro\">파일에서 읽은 값이 문자일 수도 있어요.<br>계산하기 전에 숫자로 바꿔야 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>int()로 정수 형태의 문자열을 변환할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>정수로 바꿔 더해요</h2><div class=\"example\"><pre>price_text = &quot;4500&quot;\nprice = int(price_text)\nprint(price + 500)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">출력 결과를 예상해 보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>5000</pre></div><p><code>int(\"4500\")</code>은 문자열을 정수 4500으로 바꿔요. 그 숫자에 500을 더해서 5000이 돼요. 원래 price_text는 그대로 문자열이에요.</p></details><h2 class=\"section-title\"><span>4</span>이 오류를 직접 만나보세요</h2><p>예제의 <code>price = int(price_text)</code>를 <code>price = price_text</code>로 바꾸고 실행해요. 문자열과 숫자는 그대로 더할 수 없어 <code>TypeError</code>가 나요. 확인 후 int()를 다시 넣어 고쳐보세요.</p><label class=\"question\" for=\"a-change\">오류가 난 이유와 고친 방법을 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>int()로 바꿀 수 없는 문자도 있어요</summary><p><code>int(\"4500원\")</code>이나 <code>int(\"4,500\")</code>은 <code>ValueError</code>가 나요. 오늘은 단위나 쉼표가 없는 정수 형태의 문자열만 바꿔요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 값에 따옴표가 있는지 숨긴 채 출력 결과만 보여주세요. 상대방은 어떤 추가 코드로 자료형을 확인할지 제안해요.</p></details>",
      "<h1>문자 금액을<br>진짜 합계로 바꿔요.</h1><p class=\"intro\">30002500은 우리가 원하는 합계가 아니에요.<br>값의 종류를 먼저 살펴보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>두 문자열을 정수로 변환해 합계를 구해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>교통비와 간식비가 각각 <code>\"3000\"</code>, <code>\"2500\"</code>이라는 문자열이에요. 정수로 바꿔 합계를 구하고 <code>합계: 5500</code>을 출력하세요.</p><div class=\"example\"><pre># 문자로 저장된 두 금액을 숫자로 바꾸고 더하세요.\ntransport_text = &quot;3000&quot;\nsnack_text = &quot;2500&quot;\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 양쪽 모두 바꿔요</summary><p>두 값 모두 문자열이에요. 한쪽만 바꾸면 숫자와 문자열을 더하게 돼요.</p></details><details class=\"hint\"><summary>힌트 2 · 괄호 안에 변수 이름을 넣어요</summary><p><code>int(transport_text)</code>와 <code>int(snack_text)</code>를 더해보세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>transport_text = &quot;3000&quot;\nsnack_text = &quot;2500&quot;\ntotal = int(transport_text) + int(snack_text)\nprint(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 5500</pre></div><p>int()로 변환한 두 정수를 더하기 때문에 글자 연결 대신 덧셈이 이루어져요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">숫자처럼 보이는 문자열을 더하면 어떤 문제가 생길 수 있나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 숫자와 문자열의 + 결과를 비교했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 자료형 오류를 만들고 고쳤어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 문자 금액을 정수로 바꿔 계산했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 5,
    "title": "나의 하루 지출 정리",
    "minutes": 40,
    "examples": [
      "budget = 20000\ncoffee = 4500\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
      "budget = 20000\ncoffee = 5000\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
      "# 예산 25000원, 점심 9000원, 교통 3000원\n# 간식은 문자 \"4500\"으로 기록되어 있어요.\n# 총지출과 남은 돈을 출력하세요.\n"
    ],
    "outputs": [
      "총지출: 15500\n남은 돈: 4500",
      "총지출: 16000\n남은 돈: 4000",
      null
    ],
    "solution": "budget = 25000\nlunch = 9000\ntransport = 3000\nsnack_text = \"4500\"\ntotal = lunch + transport + int(snack_text)\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
    "solutionOutput": "총지출: 16500\n남은 돈: 8500",
    "pages": [
      "<h1>나의 하루 지출을<br>한눈에 정리해요.</h1><p class=\"intro\">이번 주에 배운 것만으로 충분해요.<br>작은 질문 하나에 코드로 답해볼까요?</p><div class=\"goal\"><b>오늘의 목표</b><span>변수와 계산을 연결해 지출 요약을 만들 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · int(\"4500\")은 어떤 값이 되나요?</summary><p>문자열 \"4500\"을 정수 4500으로 바꿔요. 변환한 값은 덧셈에 사용할 수 있어요.</p></details><h2 class=\"section-title\"><span>1</span>질문부터 정해요</h2><p>오늘 예산은 <b>20,000원</b>이에요. 커피 4,500원, 점심 8,000원, 교통 3,000원을 썼어요. <b>“모두 얼마를 썼고, 얼마가 남았을까?”</b>에 답해볼게요.</p><div class=\"example\"><pre>budget = 20000\ncoffee = 4500\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>총지출: 15500\n남은 돈: 4500</pre></div><p>세 항목을 더해 총지출을 구하고, 예산에서 총지출을 빼서 남은 돈을 구해요.</p></details><h2 class=\"section-title\"><span>2</span>계산에도 순서가 있어요</h2><p>① 각 금액에 이름 붙이기<br>② 총지출 계산하기<br>③ 남은 돈 계산하기<br>④ 설명과 함께 출력하기</p><p>각 줄 앞의 <code>#</code>부터 줄 끝까지는 <b>주석</b>이에요. 설명을 적는 부분이라 파이썬이 실행하지 않아요. 미션 코드에 있는 안내도 주석이에요.</p>",
      "<h1>조건이 달라지면<br>결론은 어떻게 될까요?</h1><p class=\"intro\">데이터 분석은 숫자를 구한 뒤<br>그 숫자의 뜻을 설명하는 일이기도 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>입력값 변화가 결과에 미치는 영향을 설명해요.</span></div><h2 class=\"section-title\"><span>3</span>커피값이 500원 올랐어요</h2><label class=\"question\" for=\"a-predict\">총지출과 남은 돈은 각각 어떻게 바뀔까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"example\"><pre>budget = 20000\ncoffee = 5000\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>총지출: 16000\n남은 돈: 4000</pre></div><p>총지출은 500원 증가하고 남은 돈은 500원 감소해요. 다른 항목은 그대로 두었기 때문에 커피값의 영향만 비교할 수 있어요.</p></details><h2 class=\"section-title\"><span>4</span>예산보다 많이 쓰면?</h2><p>예제의 <code>budget = 20000</code>을 <code>budget = 15000</code>으로 바꾸고 실행하세요. 남은 돈이 음수가 되면 어떤 뜻일까요?</p><label class=\"question\" for=\"a-change\">출력된 남은 돈과 그 의미를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>해석 확인하기</summary><p><code>남은 돈: -1000</code>이 나와요. 예산 15000원보다 1000원을 더 썼다는 뜻이에요. 음수라고 계산 오류는 아니에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 금액을 수정하고, 다른 한 명은 “무엇을 바꿨는지 → 어떤 결과가 나왔는지 → 무슨 뜻인지”를 1분 안에 설명해요.</p></details>",
      "<h1>나의 첫 분석 노트를<br>완성해 보세요.</h1><p class=\"intro\">값을 정하고, 계산하고, 설명하기.<br>작아도 처음부터 끝까지 해내는 경험이에요.</p><div class=\"goal\"><b>오늘의 목표</b><span>배운 내용을 활용해 독립적인 지출 요약을 완성해요.</span></div><h2 class=\"section-title\"><span>5</span>1주차 마무리 미션</h2><p>예산 <b>25,000원</b>, 점심 <b>9,000원</b>, 교통 <b>3,000원</b>이에요. 간식비는 문자열 <code>\"4500\"</code>으로 기록돼 있어요. 각 값을 변수에 넣고 <b>총지출과 남은 돈</b>을 설명과 함께 출력하세요.</p><div class=\"example\"><pre># 예산 25000원, 점심 9000원, 교통 3000원\n# 간식은 문자 &quot;4500&quot;으로 기록되어 있어요.\n# 총지출과 남은 돈을 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 입력값부터 정리해요</summary><p>budget, lunch, transport, snack_text라는 이름을 써보세요. 이름은 달라도 괜찮아요.</p></details><details class=\"hint\"><summary>힌트 2 · 변환하고 더해요</summary><p>간식비를 int()로 바꾼 뒤 세 금액을 더해요. 남은 돈은 예산에서 총지출을 빼면 돼요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>budget = 25000\nlunch = 9000\ntransport = 3000\nsnack_text = &quot;4500&quot;\ntotal = lunch + transport + int(snack_text)\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre></div><div class=\"example\"><pre>총지출: 16500\n남은 돈: 8500</pre></div><p>9000 + 3000 + 4500 = 16500원이에요. 예산 25000원에서 빼면 8500원이 남아요. 이 기록만으로는 다른 날보다 많이 썼는지까지 알 수는 없어요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">이번 결과로 알 수 있는 사실과, 아직 알 수 없는 것을 한 가지씩 적어보세요.</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 예산과 지출을 변수로 정리했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 입력값을 바꾸고 결과를 설명했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 문자 금액을 포함한 총지출과 잔액을 구했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  }
];
