/* 1~2주차 콘텐츠. 예제는 각각 독립적으로 실행됩니다. */
window.LESSONS = [
  {
    "id": 1,
    "title": "첫 번째 코드 실행",
    "minutes": 30,
    "examples": [
      "print(\"나의 첫 데이터 분석\")\nprint(4500 + 8000)",
      "print(5000 + 8000)",
      "# 교통비 3000원과 간식비 2500원을 더해 출력하세요.\n"
    ],
    "outputs": [
      "나의 첫 데이터 분석\n12500",
      "13000",
      null
    ],
    "solution": "print(3000 + 2500)",
    "solutionOutput": "5500",
    "pages": [
      "<h1>컴퓨터에게<br>첫 계산을 부탁해요.</h1><p class=\"intro\">커피 한 잔 4,500원, 점심 한 끼 8,000원.<br>오늘 쓴 돈을 파이썬으로 더해볼까요?</p><div class=\"goal\"><b>오늘의 목표</b><span>코드를 실행하고, 숫자를 바꿔 다시 실행할 수 있어요.</span></div><h2 class=\"section-title\"><span>1</span> 코드를 실행해 보세요</h2><p>오른쪽 입력 칸이 코드를 쓰는 공간이에요. 아래 예제를 불러온 뒤 <b>실행하기</b>를 눌러보세요.</p><div class=\"example\"><pre>print(\"나의 첫 데이터 분석\")\nprint(4500 + 8000)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><ul class=\"terms\"><li><code>print()</code> 괄호 안의 내용을 화면에 보여줘요.</li><li><code>\" \"</code> 글자는 따옴표로 감싸요.</li><li><code>+</code> 숫자와 숫자를 더해요.</li></ul><h2 class=\"section-title\"><span>2</span> 결과를 비교해 보세요</h2><div class=\"example\"><pre>나의 첫 데이터 분석\n12500</pre></div><p>첫 줄에는 문장이, 둘째 줄에는 계산 결과가 나와요.<br>내 화면에도 같은 결과가 나타났나요?</p>",
      "<h1>숫자 하나를 바꾸면<br>결과도 달라질까요?</h1><p class=\"intro\">코드를 모두 외울 필요는 없어요.<br>작은 부분을 바꾸며 차이를 발견해 보세요.</p><div class=\"goal\"><b>오늘의 실험</b><span>실행 전에 예상하고, 실행 후에 확인해요.</span></div><h2 class=\"section-title\"><span>3</span> 커피값이 올랐어요</h2><p>커피값이 4,500원에서 <b>5,000원</b>으로 바뀌었어요. 점심값은 그대로 8,000원이에요.</p><p><label for=\"a-predict\">바뀐 합계는 얼마일까요? 먼저 예상해 보세요.</label></p><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"예상한 금액과 이유를 적어보세요.\"></textarea><div class=\"example\"><pre>print(5000 + 8000)</pre><button class=\"load\" data-example=\"1\">바뀐 예제로 실습하기</button></div><p>코드를 수정한 뒤에는 <b>실행하기</b>를 다시 눌러야 새로운 결과가 나타나요.</p><details class=\"hint\"><summary>결과와 설명 확인하기</summary><p>결과는 <b>13000</b>이에요. 커피값이 500원 올랐으니 합계도 12500에서 13000으로 500 증가해요.</p></details><h2 class=\"section-title\"><span>4</span> 결과를 내 말로 설명해요</h2><p><label for=\"a-change\">어느 숫자를 바꿨고, 결과는 어떻게 달라졌나요?</label></p><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"나는 …을 바꿨고, 결과는 …\"></textarea><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 사람이 금액을 바꾸면 다른 사람은 실행 결과를 예상해요. 답을 확인한 뒤 역할을 바꿔보세요.</p></details>",
      "<h1>이번에는<br>혼자 해볼 차례예요.</h1><p class=\"intro\">조금 막혀도 괜찮아요.<br>힌트를 하나씩 열어보며 완성해 보세요.</p><div class=\"goal\"><b>나의 첫 미션</b><span>두 금액의 합계를 화면에 출력해요.</span></div><h2 class=\"section-title\"><span>5</span> 오늘의 작은 문제</h2><p>교통비 <b>3,000원</b>과 간식비 <b>2,500원</b>을 썼어요. 두 금액의 합계를 출력하는 코드를 작성하세요.</p><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button><details class=\"hint\"><summary>힌트 1 · 무엇을 사용하나요?</summary><p>화면에 보여줄 때는 print(), 숫자를 더할 때는 +를 사용해요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드의 모양이 궁금해요</summary><p><code>print(첫 번째 금액 + 두 번째 금액)</code>에서 두 금액을 숫자로 바꿔보세요.</p></details><details class=\"hint\"><summary>정답과 해설 확인하기</summary><div class=\"example\"><pre>print(3000 + 2500)</pre></div><p>결과는 <b>5500</b>이에요. 괄호 안의 덧셈을 계산한 다음 print()가 화면에 보여줘요. 계산할 숫자에는 따옴표를 붙이지 않아요.</p></details><h2 class=\"section-title\"><span>6</span> 오늘의 배움을 남겨요</h2><label for=\"a-learn\">코드를 바꾼 뒤 결과를 바꾸려면 무엇을 해야 하나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"한 문장으로 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 코드를 직접 실행했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 숫자를 바꾸고 결과를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 두 금액의 합계를 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 2,
    "title": "숫자로 계산하기",
    "minutes": 30,
    "examples": [
      "print(20000 - 4500 - 8000)\nprint(4500 * 2)\nprint((4500 + 8000) / 2)",
      "print(4500 + 8000 / 2)\nprint((4500 + 8000) / 2)",
      "# 6000원짜리 샌드위치 2개와 음료 3000원\n# 총액과, 총액을 3명이 똑같이 나눈 금액을 출력하세요.\n"
    ],
    "outputs": [
      "7500\n9000\n6250.0",
      "8500.0\n6250.0",
      null
    ],
    "solution": "print(6000 * 2 + 3000)\nprint((6000 * 2 + 3000) / 3)",
    "solutionOutput": "15000\n5000.0",
    "pages": [
      "<h1>파이썬을<br>계산기로 써볼까요?</h1><p class=\"intro\">남은 돈, 두 잔의 가격, 함께 낼 돈.<br>계산 기호를 바꾸면 다른 질문에 답할 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>더하기·빼기·곱하기·나누기를 사용할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · print(3000 + 2500)의 결과는?</summary><p>5500이에요. 괄호 안을 계산한 결과를 print()가 보여줘요.</p></details><h2 class=\"section-title\"><span>1</span>계산 기호 네 가지</h2><table class=\"lesson-table\"><thead><tr><th>기호</th><th>하는 일</th><th>예</th></tr></thead><tbody><tr><td>+</td><td>더하기</td><td>3 + 2 → 5</td></tr><tr><td>-</td><td>빼기</td><td>3 - 2 → 1</td></tr><tr><td>*</td><td>곱하기</td><td>3 * 2 → 6</td></tr><tr><td>/</td><td>나누기</td><td>6 / 2 → 3.0</td></tr></tbody></table><h2 class=\"section-title\"><span>2</span>세 가지 질문을 계산해요</h2><p>① 2만 원에서 커피와 점심값을 빼면?<br>② 커피 두 잔은 얼마일까요?<br>③ 커피와 점심값의 합계를 둘이 똑같이 나누면?</p><div class=\"example\"><pre>print(20000 - 4500 - 8000)\nprint(4500 * 2)\nprint((4500 + 8000) / 2)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 설명</summary><div class=\"example\"><pre>7500\n9000\n6250.0</pre></div><p><code>/</code>로 나눈 결과는 이 예시처럼 소수점이 있는 숫자로 나와요. <code>6250.0</code>과 <code>6250</code>은 수치상 같아요.</p></details>",
      "<h1>괄호가 바꾸는<br>계산의 순서</h1><p class=\"intro\">컴퓨터는 왼쪽부터 무조건 계산하지 않아요.<br>우리가 원하는 순서를 괄호로 알려줄 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>괄호를 사용해 합계를 먼저 계산할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>어느 계산이 맞을까요?</h2><p>4,500원과 8,000원을 더한 <b>전체 금액</b>을 둘로 나누고 싶어요. 다음 두 줄은 같은 결과가 나올까요?</p><div class=\"example\"><pre>print(4500 + 8000 / 2)\nprint((4500 + 8000) / 2)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">두 줄의 결과를 실행 전에 예상해 보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 풀이 확인</summary><div class=\"example\"><pre>8500.0\n6250.0</pre></div><p>곱하기·나누기를 더하기·빼기보다 먼저 계산해요. 첫 줄은 8000만 2로 나눈 뒤 4500을 더해요. 둘째 줄은 괄호 속 합계 12500을 먼저 구한 뒤 2로 나눠요.</p></details><h2 class=\"section-title\"><span>4</span>인원수를 바꿔봐요</h2><p>둘째 줄의 <code>/ 2</code>를 <code>/ 4</code>로 바꾸고 실행하세요. 네 사람이 같은 금액을 낸다면 얼마일까요?</p><label class=\"question\" for=\"a-change\">변경한 결과와 그 의미를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>3125.0이 나와요. 12500원을 네 사람이 나눠 낼 때 한 사람이 부담하는 금액이에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 말로 계산 상황을 설명하고, 다른 한 명은 괄호가 필요한 위치를 짚어보세요.</p></details>",
      "<h1>함께 먹은 간식값을<br>나눠 계산해요.</h1><p class=\"intro\">문장을 계산식으로 바꾸는 연습이에요.<br>한 번에 어렵다면 총액부터 구해보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>총액과 1인당 금액을 두 줄로 출력할 수 있어요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>6,000원짜리 샌드위치 <b>2개</b>와 3,000원짜리 음료 <b>1개</b>를 샀어요. 총액을 출력하고, 그 총액을 <b>3명</b>이 똑같이 나눈 금액도 출력하세요.</p><div class=\"example\"><pre># 6000원짜리 샌드위치 2개와 음료 3000원\n# 총액과, 총액을 3명이 똑같이 나눈 금액을 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 총액부터 구해요</summary><p>샌드위치 가격에 개수를 곱하고 음료값을 더해요.</p></details><details class=\"hint\"><summary>힌트 2 · 나누기 전에 묶어요</summary><p>총액을 구하는 식 전체를 괄호로 묶고 3으로 나누세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>print(6000 * 2 + 3000)\nprint((6000 * 2 + 3000) / 3)</pre></div><div class=\"example\"><pre>15000\n5000.0</pre></div><p>샌드위치 합계 12000원에 음료 3000원을 더하면 15000원이에요. 이를 3으로 나누면 1인당 5000원이에요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">합계를 나누기 전에 괄호를 쓰는 이유는 무엇인가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 네 가지 계산 기호를 실행했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 괄호 유무에 따른 차이를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 총액과 1인당 금액을 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 3,
    "title": "값에 이름 붙이기",
    "minutes": 35,
    "examples": [
      "coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\nprint(total)",
      "coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\ncoffee = 5000\nprint(total)\ntotal = coffee + lunch\nprint(total)",
      "# 교통비와 간식비에 이름을 붙여 합계를 구하세요.\ntransport = 3000\nsnack = 2500\n"
    ],
    "outputs": [
      "12500",
      "12500\n13000",
      null
    ],
    "solution": "transport = 3000\nsnack = 2500\ntotal = transport + snack\nprint(\"합계:\", total)",
    "solutionOutput": "합계: 5500",
    "pages": [
      "<h1>숫자에 이름을<br>붙여보세요.</h1><p class=\"intro\">4500이 무슨 금액이었는지 헷갈리나요?<br>이름이 있으면 코드의 뜻을 읽기 쉬워져요.</p><div class=\"goal\"><b>오늘의 목표</b><span>변수에 값을 넣고 계산에 사용할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · (6000 * 2 + 3000) / 3의 결과는?</summary><p>5000.0이에요. 총액 15000을 3으로 나눈 값이에요.</p></details><h2 class=\"section-title\"><span>1</span>변수는 값을 가리키는 이름이에요</h2><p><code>coffee = 4500</code>은 “coffee라는 이름으로 4500을 사용하겠다”는 뜻이에요. <code>=</code>는 오른쪽 값을 왼쪽 이름에 넣는 <b>대입</b> 기호예요.</p><div class=\"example\"><pre>coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\nprint(total)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>12500</pre></div><p>파이썬은 위에서 아래로 실행해요. 먼저 두 금액을 정한 뒤, 그 합계를 total에 넣어요.</p></details><h2 class=\"section-title\"><span>2</span>이름을 읽어보세요</h2><ul class=\"terms\"><li><code>coffee</code>는 커피값, <code>lunch</code>는 점심값이에요.</li><li><code>total</code>은 합계라는 뜻으로 우리가 정한 이름이에요.</li><li>변수를 쓸 때는 따옴표를 붙이지 않아요. <code>\"total\"</code>은 글자 자체예요.</li><li>영문 소문자와 밑줄을 활용해요. <code>snack_price</code>처럼 쓸 수 있어요. 공백은 넣지 않고 숫자로 시작하지 않아요.</li></ul>",
      "<h1>값을 바꾸면<br>합계도 따라 바뀔까요?</h1><p class=\"intro\">계산한 값은 그 순간의 결과예요.<br>입력값이 바뀌면 합계도 다시 계산해야 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>코드의 실행 순서와 재계산을 설명할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>먼저 예상하고 실행해요</h2><div class=\"example\"><pre>coffee = 4500\nlunch = 8000\ntotal = coffee + lunch\ncoffee = 5000\nprint(total)\ntotal = coffee + lunch\nprint(total)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">두 print()는 각각 얼마를 보여줄까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>12500\n13000</pre></div><p>첫 total은 4500 + 8000의 결과인 12500이에요. coffee를 바꿔도 이미 계산한 total은 그대로예요. <code>total = coffee + lunch</code>를 다시 실행해야 13000이 돼요.</p></details><h2 class=\"section-title\"><span>4</span>설명을 붙여 출력해요</h2><p><code>print(\"합계:\", total)</code>처럼 쉼표로 구분하면 글자와 숫자를 함께 출력할 수 있어요. 기본적으로 둘 사이에 공백이 들어가요. 마지막 줄을 이 형태로 바꿔보세요.</p><label class=\"question\" for=\"a-change\">수정한 마지막 줄과 실행 결과를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><div class=\"example\"><pre>print(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 13000</pre></div></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 줄씩 읽으면서 coffee와 total이 현재 어떤 값을 가리키는지 번갈아 말해보세요.</p></details>",
      "<h1>이름을 활용해<br>지출을 정리해요.</h1><p class=\"intro\">숫자를 반복해서 쓰는 대신<br>의미가 있는 이름으로 계산해 보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>변수 두 개로 합계를 구하고 설명과 함께 출력해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>교통비는 3,000원, 간식비는 2,500원이에요. <code>transport</code>와 <code>snack</code>의 합계를 <code>total</code>에 넣고, <code>합계: 5500</code>이 나타나도록 출력하세요.</p><div class=\"example\"><pre># 교통비와 간식비에 이름을 붙여 합계를 구하세요.\ntransport = 3000\nsnack = 2500\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 값을 먼저 정해요</summary><p>변수는 사용하기 전에 값을 넣어야 해요. 두 변수를 먼저 정하고 합계를 계산하세요.</p></details><details class=\"hint\"><summary>힌트 2 · 출력할 때는 쉼표를 써요</summary><p><code>print(\"합계:\", total)</code>로 글자와 숫자를 함께 출력해요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>transport = 3000\nsnack = 2500\ntotal = transport + snack\nprint(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 5500</pre></div><p>total은 두 변수의 합계를 가리켜요. 교통비를 바꾸려면 첫 줄을 수정한 뒤 코드 전체를 다시 실행하면 돼요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">coffee를 바꾼 뒤 total을 다시 계산해야 하는 이유는 무엇인가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 변수를 만들고 사용했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 값을 바꾼 뒤 합계를 다시 계산했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 글자와 합계를 함께 출력했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 4,
    "title": "문자와 숫자 구별하기",
    "minutes": 35,
    "examples": [
      "print(3000 + 2500)\nprint(\"3000\" + \"2500\")\nprint(type(3000))\nprint(type(3.5))\nprint(type(\"3000\"))",
      "price_text = \"4500\"\nprice = int(price_text)\nprint(price + 500)",
      "# 문자로 저장된 두 금액을 숫자로 바꾸고 더하세요.\ntransport_text = \"3000\"\nsnack_text = \"2500\"\n"
    ],
    "outputs": [
      "5500\n30002500\n<class 'int'>\n<class 'float'>\n<class 'str'>",
      "5000",
      null
    ],
    "solution": "transport_text = \"3000\"\nsnack_text = \"2500\"\ntotal = int(transport_text) + int(snack_text)\nprint(\"합계:\", total)",
    "solutionOutput": "합계: 5500",
    "pages": [
      "<h1>같아 보이지만<br>다른 데이터예요.</h1><p class=\"intro\">3000과 \"3000\"은 눈으로 보면 비슷해요.<br>파이썬은 둘을 다르게 다뤄요.</p><div class=\"goal\"><b>오늘의 목표</b><span>숫자와 문자열을 구별할 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · print(\"합계:\", total)에서 따옴표를 붙인 것은?</summary><p>합계:는 보여줄 글자라서 따옴표를 붙여요. total은 변수의 값을 쓰므로 따옴표를 붙이지 않아요.</p></details><h2 class=\"section-title\"><span>1</span>따옴표가 의미를 바꿔요</h2><div class=\"example\"><pre>print(3000 + 2500)\nprint(&quot;3000&quot; + &quot;2500&quot;)\nprint(type(3000))\nprint(type(3.5))\nprint(type(&quot;3000&quot;))</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><p><code>type()</code>은 값의 종류, 즉 <b>자료형</b>을 알려줘요. <code>print(type(값))</code>으로 종류를 화면에 보여줄 수 있어요.</p><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>5500\n30002500\n&lt;class &#x27;int&#x27;&gt;\n&lt;class &#x27;float&#x27;&gt;\n&lt;class &#x27;str&#x27;&gt;</pre></div><p>숫자끼리 +를 쓰면 덧셈이에요. 문자열끼리 +를 쓰면 글자가 이어져요. <code>\"3000\"</code>과 <code>\"2500\"</code>이 이어져 <code>30002500</code>이 돼요.</p></details><h2 class=\"section-title\"><span>2</span>오늘 기억할 세 가지</h2><table class=\"lesson-table\"><thead><tr><th>자료형</th><th>뜻</th><th>예</th></tr></thead><tbody><tr><td>int</td><td>정수</td><td>3000</td></tr><tr><td>float</td><td>소수점이 있는 수</td><td>3.5</td></tr><tr><td>str</td><td>문자열</td><td>\"3000\"</td></tr></tbody></table><p>출력 모양만 보고 종류를 단정하기 어려울 때는 <code>type()</code>으로 확인해요.</p>",
      "<h1>글자로 된 금액을<br>계산하려면?</h1><p class=\"intro\">파일에서 읽은 값이 문자일 수도 있어요.<br>계산하기 전에 숫자로 바꿔야 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>int()로 정수 형태의 문자열을 변환할 수 있어요.</span></div><h2 class=\"section-title\"><span>3</span>정수로 바꿔 더해요</h2><div class=\"example\"><pre>price_text = &quot;4500&quot;\nprice = int(price_text)\nprint(price + 500)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">출력 결과를 예상해 보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>5000</pre></div><p><code>int(\"4500\")</code>은 문자열을 정수 4500으로 바꿔요. 그 숫자에 500을 더해서 5000이 돼요. 원래 price_text는 그대로 문자열이에요.</p></details><h2 class=\"section-title\"><span>4</span>이 오류를 직접 만나보세요</h2><p>예제의 <code>price = int(price_text)</code>를 <code>price = price_text</code>로 바꾸고 실행해요. 문자열과 숫자는 그대로 더할 수 없어 <code>TypeError</code>가 나요. 확인 후 int()를 다시 넣어 고쳐보세요.</p><label class=\"question\" for=\"a-change\">오류가 난 이유와 고친 방법을 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>int()로 바꿀 수 없는 문자도 있어요</summary><p><code>int(\"4500원\")</code>이나 <code>int(\"4,500\")</code>은 <code>ValueError</code>가 나요. 오늘은 단위나 쉼표가 없는 정수 형태의 문자열만 바꿔요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 값에 따옴표가 있는지 숨긴 채 출력 결과만 보여주세요. 상대방은 어떤 추가 코드로 자료형을 확인할지 제안해요.</p></details>",
      "<h1>문자 금액을<br>진짜 합계로 바꿔요.</h1><p class=\"intro\">30002500은 우리가 원하는 합계가 아니에요.<br>값의 종류를 먼저 살펴보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>두 문자열을 정수로 변환해 합계를 구해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>교통비와 간식비가 각각 <code>\"3000\"</code>, <code>\"2500\"</code>이라는 문자열이에요. 정수로 바꿔 합계를 구하고 <code>합계: 5500</code>을 출력하세요.</p><div class=\"example\"><pre># 문자로 저장된 두 금액을 숫자로 바꾸고 더하세요.\ntransport_text = &quot;3000&quot;\nsnack_text = &quot;2500&quot;\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 양쪽 모두 바꿔요</summary><p>두 값 모두 문자열이에요. 한쪽만 바꾸면 숫자와 문자열을 더하게 돼요.</p></details><details class=\"hint\"><summary>힌트 2 · 괄호 안에 변수 이름을 넣어요</summary><p><code>int(transport_text)</code>와 <code>int(snack_text)</code>를 더해보세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>transport_text = &quot;3000&quot;\nsnack_text = &quot;2500&quot;\ntotal = int(transport_text) + int(snack_text)\nprint(&quot;합계:&quot;, total)</pre></div><div class=\"example\"><pre>합계: 5500</pre></div><p>int()로 변환한 두 정수를 더하기 때문에 글자 연결 대신 덧셈이 이루어져요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">숫자처럼 보이는 문자열을 더하면 어떤 문제가 생길 수 있나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 숫자와 문자열의 + 결과를 비교했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 자료형 오류를 만들고 고쳤어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 문자 금액을 정수로 바꿔 계산했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 5,
    "title": "나의 하루 지출 정리",
    "minutes": 40,
    "examples": [
      "budget = 20000\ncoffee = 4500\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
      "budget = 20000\ncoffee = 5000\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
      "# 예산 25000원, 점심 9000원, 교통 3000원\n# 간식은 문자 \"4500\"으로 기록되어 있어요.\n# 총지출과 남은 돈을 출력하세요.\n"
    ],
    "outputs": [
      "총지출: 15500\n남은 돈: 4500",
      "총지출: 16000\n남은 돈: 4000",
      null
    ],
    "solution": "budget = 25000\nlunch = 9000\ntransport = 3000\nsnack_text = \"4500\"\ntotal = lunch + transport + int(snack_text)\nremaining = budget - total\nprint(\"총지출:\", total)\nprint(\"남은 돈:\", remaining)",
    "solutionOutput": "총지출: 16500\n남은 돈: 8500",
    "pages": [
      "<h1>나의 하루 지출을<br>한눈에 정리해요.</h1><p class=\"intro\">이번 주에 배운 것만으로 충분해요.<br>작은 질문 하나에 코드로 답해볼까요?</p><div class=\"goal\"><b>오늘의 목표</b><span>변수와 계산을 연결해 지출 요약을 만들 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · int(\"4500\")은 어떤 값이 되나요?</summary><p>문자열 \"4500\"을 정수 4500으로 바꿔요. 변환한 값은 덧셈에 사용할 수 있어요.</p></details><h2 class=\"section-title\"><span>1</span>질문부터 정해요</h2><p>오늘 예산은 <b>20,000원</b>이에요. 커피 4,500원, 점심 8,000원, 교통 3,000원을 썼어요. <b>“모두 얼마를 썼고, 얼마가 남았을까?”</b>에 답해볼게요.</p><div class=\"example\"><pre>budget = 20000\ncoffee = 4500\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>총지출: 15500\n남은 돈: 4500</pre></div><p>세 항목을 더해 총지출을 구하고, 예산에서 총지출을 빼서 남은 돈을 구해요.</p></details><h2 class=\"section-title\"><span>2</span>계산에도 순서가 있어요</h2><p>① 각 금액에 이름 붙이기<br>② 총지출 계산하기<br>③ 남은 돈 계산하기<br>④ 설명과 함께 출력하기</p><p>각 줄 앞의 <code>#</code>부터 줄 끝까지는 <b>주석</b>이에요. 설명을 적는 부분이라 파이썬이 실행하지 않아요. 미션 코드에 있는 안내도 주석이에요.</p>",
      "<h1>조건이 달라지면<br>결론은 어떻게 될까요?</h1><p class=\"intro\">데이터 분석은 숫자를 구한 뒤<br>그 숫자의 뜻을 설명하는 일이기도 해요.</p><div class=\"goal\"><b>오늘의 목표</b><span>입력값 변화가 결과에 미치는 영향을 설명해요.</span></div><h2 class=\"section-title\"><span>3</span>커피값이 500원 올랐어요</h2><label class=\"question\" for=\"a-predict\">총지출과 남은 돈은 각각 어떻게 바뀔까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"example\"><pre>budget = 20000\ncoffee = 5000\nlunch = 8000\ntransport = 3000\ntotal = coffee + lunch + transport\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>총지출: 16000\n남은 돈: 4000</pre></div><p>총지출은 500원 증가하고 남은 돈은 500원 감소해요. 다른 항목은 그대로 두었기 때문에 커피값의 영향만 비교할 수 있어요.</p></details><h2 class=\"section-title\"><span>4</span>예산보다 많이 쓰면?</h2><p>예제의 <code>budget = 20000</code>을 <code>budget = 15000</code>으로 바꾸고 실행하세요. 남은 돈이 음수가 되면 어떤 뜻일까요?</p><label class=\"question\" for=\"a-change\">출력된 남은 돈과 그 의미를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>해석 확인하기</summary><p><code>남은 돈: -1000</code>이 나와요. 예산 15000원보다 1000원을 더 썼다는 뜻이에요. 음수라고 계산 오류는 아니에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 금액을 수정하고, 다른 한 명은 “무엇을 바꿨는지 → 어떤 결과가 나왔는지 → 무슨 뜻인지”를 1분 안에 설명해요.</p></details>",
      "<h1>나의 첫 분석 노트를<br>완성해 보세요.</h1><p class=\"intro\">값을 정하고, 계산하고, 설명하기.<br>작아도 처음부터 끝까지 해내는 경험이에요.</p><div class=\"goal\"><b>오늘의 목표</b><span>배운 내용을 활용해 독립적인 지출 요약을 완성해요.</span></div><h2 class=\"section-title\"><span>5</span>1주차 마무리 미션</h2><p>예산 <b>25,000원</b>, 점심 <b>9,000원</b>, 교통 <b>3,000원</b>이에요. 간식비는 문자열 <code>\"4500\"</code>으로 기록돼 있어요. 각 값을 변수에 넣고 <b>총지출과 남은 돈</b>을 설명과 함께 출력하세요.</p><div class=\"example\"><pre># 예산 25000원, 점심 9000원, 교통 3000원\n# 간식은 문자 &quot;4500&quot;으로 기록되어 있어요.\n# 총지출과 남은 돈을 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 입력값부터 정리해요</summary><p>budget, lunch, transport, snack_text라는 이름을 써보세요. 이름은 달라도 괜찮아요.</p></details><details class=\"hint\"><summary>힌트 2 · 변환하고 더해요</summary><p>간식비를 int()로 바꾼 뒤 세 금액을 더해요. 남은 돈은 예산에서 총지출을 빼면 돼요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>budget = 25000\nlunch = 9000\ntransport = 3000\nsnack_text = &quot;4500&quot;\ntotal = lunch + transport + int(snack_text)\nremaining = budget - total\nprint(&quot;총지출:&quot;, total)\nprint(&quot;남은 돈:&quot;, remaining)</pre></div><div class=\"example\"><pre>총지출: 16500\n남은 돈: 8500</pre></div><p>9000 + 3000 + 4500 = 16500원이에요. 예산 25000원에서 빼면 8500원이 남아요. 이 기록만으로는 다른 날보다 많이 썼는지까지 알 수는 없어요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">이번 결과로 알 수 있는 사실과, 아직 알 수 없는 것을 한 가지씩 적어보세요.</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 예산과 지출을 변수로 정리했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 입력값을 바꾸고 결과를 설명했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 문자 금액을 포함한 총지출과 잔액을 구했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 6,
    "title": "여러 값을 리스트에 담기",
    "minutes": 35,
    "examples": [
      "study = [30, 45, 20, 60, 25]\nprint(study)\nprint(len(study))\nprint(sum(study))",
      "study = [30, 45, 20, 60, 25, 40]\nprint(\"기록 수:\", len(study))\nprint(\"총 시간:\", sum(study))\nprint(\"평균:\", sum(study) / len(study))",
      "# 월~금 독서 시간: 20, 30, 40, 10, 50분\n# 리스트를 만들고 기록 수, 합계, 평균을 출력하세요.\n"
    ],
    "outputs": [
      "[30, 45, 20, 60, 25]\n5\n180",
      "기록 수: 6\n총 시간: 220\n평균: 36.666666666666664",
      null
    ],
    "solution": "reading = [20, 30, 40, 10, 50]\nprint(\"기록 수:\", len(reading))\nprint(\"총 시간:\", sum(reading))\nprint(\"평균:\", sum(reading) / len(reading))",
    "solutionOutput": "기록 수: 5\n총 시간: 150\n평균: 30.0",
    "pages": [
      "<h1>여러 날의 기록을<br>한곳에 모아봐요.</h1><p class=\"intro\">하루씩 늘어나는 공부 시간.<br>날짜마다 새 변수를 만들지 않아도 돼요.</p><div class=\"goal\"><b>오늘의 목표</b><span>리스트에 여러 값을 담고 개수와 합계를 구해요.</span></div><details class=\"hint\"><summary>어제의 기억 · total = coffee + lunch는 무엇을 하나요?</summary><p>두 변수의 값을 더해 그 결과를 total에 넣어요. 이번에는 여러 값을 한 묶음으로 다뤄볼 거예요.</p></details><h2 class=\"section-title\"><span>1</span>리스트는 순서가 있는 값의 묶음이에요</h2><p>월요일부터 금요일까지 공부한 시간이 30, 45, 20, 60, 25분이에요. <b>대괄호 [ ]</b> 안에 값을 적고 <b>쉼표</b>로 구분하면 리스트가 돼요. 각 값을 <b>원소</b>라고 불러요.</p><div class=\"example\"><pre>study = [30, 45, 20, 60, 25]\nprint(study)\nprint(len(study))\nprint(sum(study))</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><h2 class=\"section-title\"><span>2</span>개수와 합계를 부탁해요</h2><ul class=\"terms\"><li><code>len(study)</code>: 리스트에 들어 있는 값의 개수</li><li><code>sum(study)</code>: 숫자 리스트의 합계</li><li>괄호 안에 처리할 값을 넣고 결과를 받는 이런 기능을 <b>함수</b>라고 해요. print()도 함수예요.</li></ul><details class=\"hint\"><summary>예상 결과와 해설</summary><div class=\"example\"><pre>[30, 45, 20, 60, 25]\n5\n180</pre></div><p>기록은 5개이고 총 공부 시간은 180분이에요. 리스트의 순서는 입력한 순서대로 유지돼요.</p></details>",
      "<h1>하루를 더 기록하면<br>평균은 어떻게 될까요?</h1><p class=\"intro\">합계가 늘었다고<br>평균도 반드시 늘어나는 것은 아니에요.</p><div class=\"goal\"><b>오늘의 목표</b><span>합계 ÷ 개수로 기록당 평균을 구해요.</span></div><h2 class=\"section-title\"><span>3</span>토요일 40분을 추가해요</h2><label class=\"question\" for=\"a-predict\">6일간의 합계와 평균은 얼마일지 예상해 보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"example\"><pre>study = [30, 45, 20, 60, 25, 40]\nprint(&quot;기록 수:&quot;, len(study))\nprint(&quot;총 시간:&quot;, sum(study))\nprint(&quot;평균:&quot;, sum(study) / len(study))</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>기록 수: 6\n총 시간: 220\n평균: 36.666666666666664</pre></div><p>220분을 6개 기록으로 나누면 약 36.67분이에요. 컴퓨터의 소수 표현 때문에 출력이 이렇게 보일 수 있어요. 여기서는 반올림하지 않고 결과를 읽어요.</p></details><h2 class=\"section-title\"><span>4</span>40분 대신 0분이었다면?</h2><p>리스트의 마지막 40을 0으로 바꾸세요. 이번에는 <b>공부를 하지 않았다고 확인한 날</b>이에요. 0도 하나의 기록으로 포함해요.</p><label class=\"question\" for=\"a-change\">기록 수·합계·평균이 어떻게 달라졌나요?</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>기록 수는 6, 합계는 180, 평균은 30.0이에요. 기록을 아예 빼면 5일 평균 36.0이 되므로 다른 질문에 답하게 돼요. 모르는 값을 무조건 0으로 채우면 안 돼요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>“0분을 기록한 날”과 “기록하지 않아 모르는 날”은 어떤 차이가 있는지 설명해 보세요.</p></details>",
      "<h1>나의 독서 기록을<br>요약해 보세요.</h1><p class=\"intro\">숫자를 하나의 묶음으로 만들면<br>같은 방법으로 여러 기록을 분석할 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>리스트의 개수·합계·평균을 출력해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>월~금 독서 시간이 <b>20, 30, 40, 10, 50분</b>이에요. 리스트를 만들고 기록 수, 총 시간, 평균을 차례대로 출력하세요.</p><div class=\"example\"><pre># 월~금 독서 시간: 20, 30, 40, 10, 50분\n# 리스트를 만들고 기록 수, 합계, 평균을 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 방향 잡기</summary><p>대괄호 안에 다섯 값을 순서대로 넣어요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드로 옮기기</summary><p>len(), sum()을 쓰고 합계를 개수로 나누세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>reading = [20, 30, 40, 10, 50]\nprint(&quot;기록 수:&quot;, len(reading))\nprint(&quot;총 시간:&quot;, sum(reading))\nprint(&quot;평균:&quot;, sum(reading) / len(reading))</pre></div><div class=\"example\"><pre>기록 수: 5\n총 시간: 150\n평균: 30.0</pre></div><p>평균 30.0분은 다섯 기록의 합계 150분을 5로 나눈 값이에요. 매일 정확히 30분 읽었다는 뜻은 아니에요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">평균만 보고는 알 수 없는 정보는 무엇인가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 리스트를 만들고 출력했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 0분 기록을 넣었을 때의 차이를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 개수·합계·평균을 계산했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 7,
    "title": "인덱스와 슬라이싱",
    "minutes": 35,
    "examples": [
      "study = [30, 45, 20, 60, 25]\nprint(study[0])\nprint(study[2])\nprint(study[-1])",
      "study = [30, 45, 20, 60, 25]\nprint(study[0:3])\nprint(study[3:5])\nprint(sum(study[0:3]))",
      "# 월~금 지출: 7000, 9000, 6000, 12000, 8000원\n# 첫날, 마지막 날, 화~목 지출 합계를 출력하세요.\n"
    ],
    "outputs": [
      "30\n20\n25",
      "[30, 45, 20]\n[60, 25]\n95",
      null
    ],
    "solution": "spending = [7000, 9000, 6000, 12000, 8000]\nprint(\"첫날:\", spending[0])\nprint(\"마지막 날:\", spending[-1])\nprint(\"화~목 합계:\", sum(spending[1:4]))",
    "solutionOutput": "첫날: 7000\n마지막 날: 8000\n화~목 합계: 27000",
    "pages": [
      "<h1>묶음 속에서<br>원하는 값을 꺼내요.</h1><p class=\"intro\">다섯 기록 가운데 수요일 값만 궁금해요.<br>리스트의 위치 번호를 사용하면 돼요.</p><div class=\"goal\"><b>오늘의 목표</b><span>0부터 시작하는 인덱스로 값을 선택해요.</span></div><details class=\"hint\"><summary>어제의 기억 · len([30, 45, 20])의 결과는?</summary><p>값이 3개이므로 3이에요. 값의 개수와 마지막 위치 번호는 달라요.</p></details><h2 class=\"section-title\"><span>1</span>첫 번째 위치 번호는 0이에요</h2><p>리스트의 위치 번호를 <b>인덱스</b>라고 해요. <code>study[0]</code>은 첫 번째 값을 꺼내요.</p><table class=\"lesson-table\"><thead><tr><th>요일</th><th>월</th><th>화</th><th>수</th><th>목</th><th>금</th></tr></thead><tbody><tr><th>값</th><td>30</td><td>45</td><td>20</td><td>60</td><td>25</td></tr><tr><th>인덱스</th><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td></tr></tbody></table><div class=\"example\"><pre>study = [30, 45, 20, 60, 25]\nprint(study[0])\nprint(study[2])\nprint(study[-1])</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 해설</summary><div class=\"example\"><pre>30\n20\n25</pre></div><p>2번 위치는 세 번째 값이에요. <code>-1</code>은 뒤에서 첫 번째, 즉 마지막 값을 뜻해요.</p></details><h2 class=\"section-title\"><span>2</span>존재하지 않는 위치는 꺼낼 수 없어요</h2><p>다섯 값의 인덱스는 0~4예요. <code>study[5]</code>는 범위를 벗어나 <code>IndexError</code>가 나요. <code>len(study)</code>는 5지만 마지막 인덱스는 4예요.</p>",
      "<h1>한 값이 아니라<br>일부 구간을 꺼내요.</h1><p class=\"intro\">월요일부터 수요일까지 묶어서 보고 싶어요.<br>시작과 끝 위치를 정해 잘라보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>끝 위치를 제외하는 슬라이싱을 이해해요.</span></div><h2 class=\"section-title\"><span>3</span>[시작:끝]으로 잘라요</h2><p><code>study[0:3]</code>은 0번부터 <b>3번 직전</b>까지예요. 이런 구간 선택을 <b>슬라이싱</b>이라고 해요. 결과도 리스트예요.</p><div class=\"example\"><pre>study = [30, 45, 20, 60, 25]\nprint(study[0:3])\nprint(study[3:5])\nprint(sum(study[0:3]))</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 설명</summary><div class=\"example\"><pre>[30, 45, 20]\n[60, 25]\n95</pre></div><p>첫 구간은 월~수, 둘째 구간은 목~금이에요. 잘라낸 숫자 리스트에도 sum()을 쓸 수 있어요.</p></details><h2 class=\"section-title\"><span>4</span>화요일부터 목요일까지</h2><label class=\"question\" for=\"a-predict\">화~목을 선택하려면 대괄호 안에 어떤 시작·끝 번호를 써야 할까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><p>첫 줄의 <code>study[0:3]</code>을 바꿔 실행해 보세요. 세 번째 합계 줄도 같은 구간으로 바꿔보세요.</p><label class=\"question\" for=\"a-change\">바꾼 슬라이싱과 그 합계를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><div class=\"example\"><pre>study[1:4]</pre></div><p>선택된 값은 [45, 20, 60], 합계는 125예요. 마지막에 포함할 위치 3보다 하나 큰 4를 끝으로 써요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명은 “첫 세 날”, “마지막 두 날” 같은 구간을 말하고 다른 한 명은 시작·끝 인덱스를 설명해요.</p></details>",
      "<h1>필요한 날짜만<br>선택해 보세요.</h1><p class=\"intro\">전체를 더하는 것과 일부를 더하는 것은<br>서로 다른 질문에 대한 답이에요.</p><div class=\"goal\"><b>오늘의 목표</b><span>인덱스와 슬라이싱을 구별해 사용해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>월~금 지출이 <b>7000, 9000, 6000, 12000, 8000원</b>이에요. 첫날 지출, 마지막 날 지출, 화~목 지출 합계를 설명과 함께 출력하세요.</p><div class=\"example\"><pre># 월~금 지출: 7000, 9000, 6000, 12000, 8000원\n# 첫날, 마지막 날, 화~목 지출 합계를 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 방향 잡기</summary><p>첫날은 [0], 마지막 날은 [-1]로 꺼내요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드로 옮기기</summary><p>화~목은 [1:4]로 선택한 뒤 sum()으로 더해요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>spending = [7000, 9000, 6000, 12000, 8000]\nprint(&quot;첫날:&quot;, spending[0])\nprint(&quot;마지막 날:&quot;, spending[-1])\nprint(&quot;화~목 합계:&quot;, sum(spending[1:4]))</pre></div><div class=\"example\"><pre>첫날: 7000\n마지막 날: 8000\n화~목 합계: 27000</pre></div><p>화~목 합계는 9000 + 6000 + 12000 = 27000원이에요. [1:3]으로 자르면 목요일이 빠져요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">study[2]와 study[0:2]는 어떻게 다른가요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 0부터 시작하는 위치를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 끝 위치가 제외되는 것을 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 특정 값과 구간 합계를 구했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 8,
    "title": "조건에 따라 판단하기",
    "minutes": 35,
    "examples": [
      "minutes = 35\nprint(minutes >= 30)\nif minutes >= 30:\n    print(\"목표 달성\")\nelse:\n    print(\"조금 더 해봐요\")",
      "minutes = 30\nif minutes >= 30:\n    print(\"목표 달성\")\nelse:\n    print(\"미달성\")",
      "# 오늘 지출은 12000원이에요.\n# 10000원 초과이면 \"예산 초과\", 아니면 \"예산 이내\"를 출력하세요.\n"
    ],
    "outputs": [
      "True\n목표 달성",
      "목표 달성",
      null
    ],
    "solution": "spending = 12000\nif spending > 10000:\n    print(\"예산 초과\")\nelse:\n    print(\"예산 이내\")",
    "solutionOutput": "예산 초과",
    "pages": [
      "<h1>조건에 따라<br>다르게 말해줘요.</h1><p class=\"intro\">30분 이상 공부하면 목표 달성이에요.<br>파이썬에게 판단 기준을 알려주세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>비교 결과와 if·else의 동작을 이해해요.</span></div><details class=\"hint\"><summary>어제의 기억 · study[0]은 어떤 값을 꺼내나요?</summary><p>첫 번째 값을 꺼내요. 그 값이 목표 이상인지 비교할 수도 있어요.</p></details><h2 class=\"section-title\"><span>1</span>비교하면 참 또는 거짓이 나와요</h2><p><code>35 &gt;= 30</code>은 “35가 30 이상인가?”예요. 맞으면 <code>True</code>(참), 아니면 <code>False</code>(거짓)가 나와요.</p><table class=\"lesson-table\"><thead><tr><th>기호</th><th>뜻</th></tr></thead><tbody><tr><td>&gt; / &lt;</td><td>초과 / 미만</td></tr><tr><td>&gt;= / &lt;=</td><td>이상 / 이하</td></tr><tr><td>== / !=</td><td>같음 / 다름</td></tr></tbody></table><div class=\"example\"><pre>minutes = 35\nprint(minutes &gt;= 30)\nif minutes &gt;= 30:\n    print(&quot;목표 달성&quot;)\nelse:\n    print(&quot;조금 더 해봐요&quot;)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과</summary><div class=\"example\"><pre>True\n목표 달성</pre></div></details><h2 class=\"section-title\"><span>2</span>조건과 실행할 일을 나눠요</h2><p><code>if 조건:</code> 아래에는 참일 때 할 일을 써요. <code>else:</code> 아래에는 거짓일 때 할 일을 써요. 콜론 <code>:</code>을 붙이고, 각 내부 줄은 <b>공백 네 칸</b> 들여써요. else는 if와 같은 위치에 써요.</p>",
      "<h1>정확히 30분이면<br>달성일까요?</h1><p class=\"intro\">경계에 있는 값으로 확인하면<br>조건을 제대로 썼는지 알 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>이상과 초과의 차이를 경계값으로 확인해요.</span></div><h2 class=\"section-title\"><span>3</span>먼저 예상하고 실행해요</h2><div class=\"example\"><pre>minutes = 30\nif minutes &gt;= 30:\n    print(&quot;목표 달성&quot;)\nelse:\n    print(&quot;미달성&quot;)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">30분이면 어느 문장이 출력될까요? 이유도 적어보세요.</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 설명</summary><div class=\"example\"><pre>목표 달성</pre></div><p>&gt;=는 같은 값도 포함해요. 30은 30 이상이므로 목표 달성이에요.</p></details><h2 class=\"section-title\"><span>4</span>조건 하나만 바꿔봐요</h2><p><code>&gt;=</code>를 <code>&gt;</code>로 바꾸고 실행하세요. 다음으로 원래 조건 &gt;=를 되돌린 뒤 minutes를 29, 30, 31로 바꾸어 각각 확인해요.</p><label class=\"question\" for=\"a-change\">29·30·31분의 결과와 >를 썼을 때의 차이를 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>&gt;= 30에서는 29는 미달성, 30과 31은 달성이에요. &gt; 30에서는 30도 미달성이에요. <code>=</code>는 대입이고, 같은지 비교할 때는 <code>==</code>를 써요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>“만원 이상”과 “만원 초과”라는 조건을 각각 코드로 표현하고 10000을 넣어 차이를 확인해요.</p></details>",
      "<h1>지출이 기준을<br>넘었는지 판단해요.</h1><p class=\"intro\">어떤 값을 포함할지<br>문제의 표현을 꼼꼼하게 읽어보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>초과 조건과 두 가지 출력을 작성해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>오늘 지출은 <b>12000원</b>이에요. <b>10000원 초과</b>이면 “예산 초과”, 아니면 “예산 이내”를 출력하세요. 완성 후 10000원과 9000원도 넣어 확인하세요.</p><div class=\"example\"><pre># 오늘 지출은 12000원이에요.\n# 10000원 초과이면 &quot;예산 초과&quot;, 아니면 &quot;예산 이내&quot;를 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 방향 잡기</summary><p>초과는 >예요. 같은 10000원은 초과가 아니에요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드로 옮기기</summary><p>if spending > 10000:과 else: 아래에서 각각 출력해요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>spending = 12000\nif spending &gt; 10000:\n    print(&quot;예산 초과&quot;)\nelse:\n    print(&quot;예산 이내&quot;)</pre></div><div class=\"example\"><pre>예산 초과</pre></div><p>12000원은 예산 초과예요. 10000원과 9000원은 모두 예산 이내예요. 들여쓴 두 출력 중 조건에 맞는 하나만 실행돼요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">if 아래 들여쓰기는 어떤 역할을 하나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 참·거짓과 조건 분기를 실행했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 기준과 같은 값을 넣어 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 초과와 이내를 구분하는 코드를 썼어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 9,
    "title": "반복해서 기록 살펴보기",
    "minutes": 35,
    "examples": [
      "study = [20, 40, 30]\nfor minutes in study:\n    print(minutes)",
      "study = [20, 40, 30]\nfor minutes in study:\n    if minutes >= 30:\n        print(\"달성:\", minutes)",
      "# 공부 시간은 15, 45, 30, 20분이에요.\n# 각 값을 살펴보며 30분 이상인 값만 출력하세요.\n"
    ],
    "outputs": [
      "20\n40\n30",
      "달성: 40\n달성: 30",
      null
    ],
    "solution": "study = [15, 45, 30, 20]\nfor minutes in study:\n    if minutes >= 30:\n        print(minutes)",
    "solutionOutput": "45\n30",
    "pages": [
      "<h1>하나씩 꺼내서<br>같은 일을 반복해요.</h1><p class=\"intro\">값이 열 개, 백 개로 늘어나도<br>출력 코드를 매번 더 쓸 필요는 없어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>for로 리스트의 값을 순서대로 처리해요.</span></div><details class=\"hint\"><summary>어제의 기억 · 30 >= 30의 결과는?</summary><p>True예요. “이상”에는 같은 값도 포함돼요. 오늘은 여러 값에 같은 조건을 적용해요.</p></details><h2 class=\"section-title\"><span>1</span>for가 값을 하나씩 꺼내요</h2><div class=\"example\"><pre>study = [20, 40, 30]\nfor minutes in study:\n    print(minutes)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><p><code>for minutes in study:</code>는 study에서 값을 하나씩 꺼내 minutes에 넣어요. minutes는 우리가 정한 변수 이름이에요. 들여쓴 코드를 실행하고 다음 값으로 넘어가요.</p><details class=\"hint\"><summary>예상 결과와 해설</summary><div class=\"example\"><pre>20\n40\n30</pre></div><p>minutes가 20 → 40 → 30으로 바뀌며 print()가 세 번 실행돼요. 첫 줄의 리스트 순서와 같아요.</p></details><h2 class=\"section-title\"><span>2</span>반복할 줄은 들여써요</h2><p>for 줄 끝에는 콜론이 있어요. 반복할 출력 줄은 공백 네 칸 들여써요. 들여쓰기를 없애면 반복문의 내용이 없어져 오류가 나요. 실행 창에서는 Tab 키로 공백 네 칸을 넣을 수 있어요.</p>",
      "<h1>모든 기록에서<br>조건에 맞는 값만 찾아요.</h1><p class=\"intro\">리스트를 순회하면서<br>각 값이 기준에 맞는지 판단해 보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>for 안에 if를 넣어 값을 골라 출력해요.</span></div><h2 class=\"section-title\"><span>3</span>반복 안에서 한 번 더 판단해요</h2><div class=\"example\"><pre>study = [20, 40, 30]\nfor minutes in study:\n    if minutes &gt;= 30:\n        print(&quot;달성:&quot;, minutes)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><label class=\"question\" for=\"a-predict\">어떤 값이 어떤 순서로 출력될까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>결과와 실행 흐름</summary><div class=\"example\"><pre>달성: 40\n달성: 30</pre></div><p>20은 조건이 거짓이라 출력하지 않아요. 40과 30은 참이라 출력해요. for 안의 if는 네 칸, if 안의 print는 <b>여덟 칸</b> 들여써요. print가 두 단계 안에 있기 때문이에요.</p></details><h2 class=\"section-title\"><span>4</span>기준을 40분으로 바꿔요</h2><p>조건을 <code>minutes &gt;= 40</code>으로 바꿔 실행하세요. 이어서 60으로도 바꿔보세요.</p><label class=\"question\" for=\"a-change\">40분 기준과 60분 기준에서 각각 무엇이 출력됐나요?</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>40분 기준에서는 “달성: 40”만 출력돼요. 60분 기준에서는 출력이 없어요. 모든 값이 조건을 만족하지 않아 출력 줄이 실행되지 않았기 때문이에요. 출력이 없다고 항상 오류인 것은 아니에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>한 명이 리스트의 값을 차례대로 읽으면 다른 한 명은 조건의 참·거짓과 출력 여부를 말해요.</p></details>",
      "<h1>목표를 달성한<br>기록만 꺼내보세요.</h1><p class=\"intro\">기준을 적용하는 방법은<br>다른 숫자 기록에도 그대로 쓸 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>리스트 전체를 살펴 조건에 맞는 값을 출력해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>공부 시간은 <b>15, 45, 30, 20분</b>이에요. for로 하나씩 살펴보고 <b>30분 이상</b>인 값만 한 줄씩 출력하세요.</p><div class=\"example\"><pre># 공부 시간은 15, 45, 30, 20분이에요.\n# 각 값을 살펴보며 30분 이상인 값만 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 방향 잡기</summary><p>리스트의 네 값을 하나씩 minutes에 넣도록 for를 써요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드로 옮기기</summary><p>for 안에 if minutes >= 30:을 쓰고 그 안에 print(minutes)를 넣어요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>study = [15, 45, 30, 20]\nfor minutes in study:\n    if minutes &gt;= 30:\n        print(minutes)</pre></div><div class=\"example\"><pre>45\n30</pre></div><p>45와 30이 원래 리스트 순서대로 출력돼요. 같은 값이 여러 번 들어 있다면 각 기록을 따로 처리해요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">반복문과 조건문은 각각 어떤 일을 맡았나요?</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> for로 값을 하나씩 출력했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 조건을 바꿔 출력 차이를 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 두 단계 들여쓰기로 조건에 맞는 값을 골랐어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  },
  {
    "id": 10,
    "title": "주간 기록 분석하기",
    "minutes": 40,
    "examples": [
      "study = [20, 40, 30, 15, 50]\ncount = 0\nfor minutes in study:\n    if minutes >= 30:\n        count = count + 1\nprint(\"달성일:\", count)",
      "study = [20, 40, 30, 15, 50]\ncount = 0\nfor minutes in study:\n    if minutes >= 30:\n        count = count + 1\nprint(\"총 시간:\", sum(study))\nprint(\"평균:\", sum(study) / len(study))\nprint(\"달성일:\", count)",
      "# 월~금 공부 시간: 25, 40, 35, 20, 50분\n# 총 시간, 평균, 30분 이상 달성일 수를 출력하세요.\n"
    ],
    "outputs": [
      "달성일: 3",
      "총 시간: 155\n평균: 31.0\n달성일: 3",
      null
    ],
    "solution": "study = [25, 40, 35, 20, 50]\ncount = 0\nfor minutes in study:\n    if minutes >= 30:\n        count = count + 1\nprint(\"총 시간:\", sum(study))\nprint(\"평균:\", sum(study) / len(study))\nprint(\"달성일:\", count)",
    "solutionOutput": "총 시간: 170\n평균: 34.0\n달성일: 3",
    "pages": [
      "<h1>목표를 달성한 날은<br>모두 며칠일까요?</h1><p class=\"intro\">이번 주에 배운 리스트·조건·반복을<br>하나의 질문으로 연결해 보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>조건에 맞는 기록 수를 변수로 셀 수 있어요.</span></div><details class=\"hint\"><summary>어제의 기억 · for 안에 if를 넣으면 무엇을 할 수 있나요?</summary><p>모든 기록을 하나씩 살펴 조건에 맞는 값만 처리할 수 있어요.</p></details><h2 class=\"section-title\"><span>1</span>세기 위한 변수를 준비해요</h2><p>반복 전에 <code>count = 0</code>으로 시작해요. 목표를 달성한 값을 만날 때마다 <code>count = count + 1</code>로 하나씩 늘려요. 오른쪽을 먼저 계산해 왼쪽에 다시 넣어요.</p><div class=\"example\"><pre>study = [20, 40, 30, 15, 50]\ncount = 0\nfor minutes in study:\n    if minutes &gt;= 30:\n        count = count + 1\nprint(&quot;달성일:&quot;, count)</pre><button class=\"load\" data-example=\"0\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 해설</summary><div class=\"example\"><pre>달성일: 3</pre></div><p>40, 30, 50분을 만날 때 count가 1, 2, 3이 돼요. 마지막 print는 들여쓰지 않아 반복이 끝난 뒤 한 번 실행돼요.</p></details><h2 class=\"section-title\"><span>2</span>count = 0의 위치를 확인해요</h2><p>count를 for 안에서 0으로 만들면 매 기록마다 이전 개수를 잊어버려요. <b>시작값은 반복 전에</b> 한 번 정해야 해요. 오늘은 하루에 기록 하나가 있으므로 기록 수가 곧 일수예요.</p>",
      "<h1>합계, 평균, 달성일을<br>함께 읽어보세요.</h1><p class=\"intro\">평균이 높아도<br>매일 목표를 달성한 것은 아닐 수 있어요.</p><div class=\"goal\"><b>오늘의 목표</b><span>서로 다른 요약 지표의 뜻을 구분해요.</span></div><h2 class=\"section-title\"><span>3</span>세 가지 결과를 출력해요</h2><div class=\"example\"><pre>study = [20, 40, 30, 15, 50]\ncount = 0\nfor minutes in study:\n    if minutes &gt;= 30:\n        count = count + 1\nprint(&quot;총 시간:&quot;, sum(study))\nprint(&quot;평균:&quot;, sum(study) / len(study))\nprint(&quot;달성일:&quot;, count)</pre><button class=\"load\" data-example=\"1\">이 예제로 실습하기</button></div><details class=\"hint\"><summary>예상 결과와 설명</summary><div class=\"example\"><pre>총 시간: 155\n평균: 31.0\n달성일: 3</pre></div><p>하루 평균은 31분이지만, 30분 이상 공부한 날은 5일 중 3일이에요. 평균만으로 꾸준함을 단정하지 않아요.</p></details><h2 class=\"section-title\"><span>4</span>기준을 바꿔 비교해요</h2><label class=\"question\" for=\"a-predict\">달성 기준을 40분 이상으로 바꾸면 합계·평균·달성일은 어떻게 될까요?</label><textarea class=\"answer\" id=\"a-predict\" data-answer=\"predict\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><p>조건의 30을 40으로 바꿔 실행하고 예상과 비교하세요. 원래 공부 시간은 바꾸지 않아요.</p><label class=\"question\" for=\"a-change\">바뀐 지표와 바뀌지 않은 지표를 구분해 적어보세요.</label><textarea class=\"answer\" id=\"a-change\" data-answer=\"change\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><details class=\"hint\"><summary>확인하기</summary><p>달성일은 2일이에요. 합계 155분과 평균 31.0분은 그대로예요. 입력 기록은 같고 목표 판단 기준만 달라졌기 때문이에요.</p></details><details class=\"hint\"><summary>함께 공부한다면</summary><p>같은 기록에 30분과 40분이라는 기준을 적용해 각자 설명해요. 보고할 때 기준을 함께 말해야 하는 이유도 이야기해 보세요.</p></details>",
      "<h1>나의 주간 학습<br>보고서를 완성해요.</h1><p class=\"intro\">코드를 실행하고<br>결과를 두 문장으로 설명해 보세요.</p><div class=\"goal\"><b>오늘의 목표</b><span>기록 전체의 요약과 조건별 개수를 함께 구해요.</span></div><h2 class=\"section-title\"><span>5</span>오늘의 작은 문제</h2><p>월~금 공부 시간은 <b>25, 40, 35, 20, 50분</b>이에요. 총 시간, 하루 평균, <b>30분 이상</b> 공부한 날의 수를 출력하세요.</p><div class=\"example\"><pre># 월~금 공부 시간: 25, 40, 35, 20, 50분\n# 총 시간, 평균, 30분 이상 달성일 수를 출력하세요.\n</pre><button class=\"load\" data-example=\"2\">미션 코드로 시작하기</button></div><details class=\"hint\"><summary>힌트 1 · 방향 잡기</summary><p>개수 변수는 반복 전에 0으로 만들어요. 조건을 만족할 때만 1을 더해요.</p></details><details class=\"hint\"><summary>힌트 2 · 코드로 옮기기</summary><p>for와 if가 끝난 다음 sum(), len(), count를 활용해 세 줄을 출력하세요.</p></details><details class=\"hint\"><summary>정답과 해설</summary><div class=\"example\"><pre>study = [25, 40, 35, 20, 50]\ncount = 0\nfor minutes in study:\n    if minutes &gt;= 30:\n        count = count + 1\nprint(&quot;총 시간:&quot;, sum(study))\nprint(&quot;평균:&quot;, sum(study) / len(study))\nprint(&quot;달성일:&quot;, count)</pre></div><div class=\"example\"><pre>총 시간: 170\n평균: 34.0\n달성일: 3</pre></div><p>총 170분, 하루 평균 34분, 목표 달성은 5일 중 3일이에요. “평균이 30분 이상이므로 매일 달성했다”는 해석은 맞지 않아요.</p></details><h2 class=\"section-title\"><span>6</span>오늘의 배움을 남겨요</h2><label class=\"question\" for=\"a-learn\">분석 결과를 두 문장으로 요약하고, 이 기록만으로 알 수 없는 점도 적어보세요.</label><textarea class=\"answer\" id=\"a-learn\" data-answer=\"learn\" placeholder=\"생각한 내용을 적어보세요.\"></textarea><div class=\"checks\"><label><input type=\"checkbox\" data-check=\"run\"> 리스트·조건·반복을 연결했어요.</label><label><input type=\"checkbox\" data-check=\"change\"> 목표 기준 변경의 영향을 확인했어요.</label><label><input type=\"checkbox\" data-check=\"solve\"> 합계·평균·달성일을 계산하고 설명했어요.</label></div><button class=\"complete\" id=\"complete\">오늘의 학습 마치기</button><p class=\"success\" id=\"completion\" role=\"status\"></p><button class=\"next-day\" id=\"nextDay\" hidden>다음 날 학습 열기</button>"
    ]
  }
];
